import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AuthListener } from '@/components/AuthListener'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Expenses 3.0',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en' className='h-full bg-slate-900'>
            <body className={`${inter.className} h-full`}>
                <AuthListener />
                {children}
            </body>
        </html>
    )
}
