import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AuthListener } from '@/components/AuthListener'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Expenses 3.0',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en' className='h-full'>
            <body className={`${inter.className} h-full`}>
                <Toaster position='bottom-right' reverseOrder toastOptions={{ duration: 5000 }} />
                {children}
            </body>
        </html>
    )
}
